apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-provisioner.fullname" . }}-config
data:
  AWS_DEFAULT_REGION: {{ .Values.config.awsRegion | quote }}
  LOCALSTACK_ENDPOINT: {{ .Values.config.localstackEndpoint | quote }}
  TERRAFORM_STATE_BUCKET: {{ .Values.config.terraformStateBucket | quote }}
  TERRAFORM_STATE_DYNAMODB_TABLE: {{ .Values.config.terraformStateDynamodbTable | quote }}
  TERRAFORM_WORKING_DIR: {{ .Values.config.terraformWorkingDir | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
