apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-provisioner.fullname" . }}-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
